// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefactorizacionService.Data;

#nullable disable

namespace RefactorizacionService.Migrations
{
    [DbContext(typeof(RefactorizacionDbContext))]
    [Migration("20251108035612_InitialRefactorizacion")]
    partial class InitialRefactorizacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RefactorizacionService.Models.DependenciaRefactorizada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoRefactorizado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LineaFin")
                        .HasColumnType("int");

                    b.Property<int>("LineaInicio")
                        .HasColumnType("int");

                    b.Property<string>("NombreClase")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreMetodo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RefactorizacionHistorialId")
                        .HasColumnType("int");

                    b.Property<string>("ServicioOriginal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoRefactorizacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RefactorizacionHistorialId");

                    b.ToTable("DependenciasRefactorizadas");
                });

            modelBuilder.Entity("RefactorizacionService.Models.RefactorizacionHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDependenciasRefactorizadas")
                        .HasColumnType("int");

                    b.Property<string>("CodigoDiff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaRefactorizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MensajeError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuloRefactorizado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("RefactorizacionHistorial");
                });

            modelBuilder.Entity("RefactorizacionService.Models.ServicioMigrado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaMigracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreModulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Puerto")
                        .HasColumnType("int");

                    b.Property<string>("UrlMicroservicio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NombreProyecto", "NombreModulo")
                        .IsUnique();

                    b.ToTable("ServiciosMigrados");
                });

            modelBuilder.Entity("RefactorizacionService.Models.DependenciaRefactorizada", b =>
                {
                    b.HasOne("RefactorizacionService.Models.RefactorizacionHistorial", "Historial")
                        .WithMany("DependenciasRefactorizadas")
                        .HasForeignKey("RefactorizacionHistorialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("RefactorizacionService.Models.RefactorizacionHistorial", b =>
                {
                    b.Navigation("DependenciasRefactorizadas");
                });
#pragma warning restore 612, 618
        }
    }
}
