// <auto-generated />
using System;
using ContainerizationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContainerizationService.Migrations
{
    [DbContext(typeof(ContainerizationDbContext))]
    partial class ContainerizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContainerizationService.Models.MicroserviceContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenedorId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DockerComposeFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DockerfilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaUltimaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ImagenDocker")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Logs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreModulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PuertoAsignado")
                        .HasColumnType("int");

                    b.Property<string>("RutaMicroservicio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ContenedorId")
                        .HasDatabaseName("IX_MicroserviceContainers_ContenedorId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_MicroserviceContainers_Estado");

                    b.HasIndex("NombreModulo")
                        .IsUnique()
                        .HasDatabaseName("IX_MicroserviceContainers_NombreModulo");

                    b.ToTable("MicroserviceContainers", (string)null);
                });

            modelBuilder.Entity("ContainerizationService.Models.PortAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnUso")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLiberacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MicroserviceContainerId")
                        .HasColumnType("int");

                    b.Property<int>("Puerto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnUso")
                        .HasDatabaseName("IX_PortAssignments_EnUso");

                    b.HasIndex("MicroserviceContainerId")
                        .IsUnique()
                        .HasFilter("[MicroserviceContainerId] IS NOT NULL");

                    b.HasIndex("Puerto")
                        .IsUnique()
                        .HasDatabaseName("IX_PortAssignments_Puerto");

                    b.ToTable("PortAssignments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnUso = false,
                            Puerto = 6000
                        },
                        new
                        {
                            Id = 2,
                            EnUso = false,
                            Puerto = 6001
                        },
                        new
                        {
                            Id = 3,
                            EnUso = false,
                            Puerto = 6002
                        },
                        new
                        {
                            Id = 4,
                            EnUso = false,
                            Puerto = 6003
                        },
                        new
                        {
                            Id = 5,
                            EnUso = false,
                            Puerto = 6004
                        },
                        new
                        {
                            Id = 6,
                            EnUso = false,
                            Puerto = 6005
                        },
                        new
                        {
                            Id = 7,
                            EnUso = false,
                            Puerto = 6006
                        },
                        new
                        {
                            Id = 8,
                            EnUso = false,
                            Puerto = 6007
                        },
                        new
                        {
                            Id = 9,
                            EnUso = false,
                            Puerto = 6008
                        },
                        new
                        {
                            Id = 10,
                            EnUso = false,
                            Puerto = 6009
                        },
                        new
                        {
                            Id = 11,
                            EnUso = false,
                            Puerto = 6010
                        },
                        new
                        {
                            Id = 12,
                            EnUso = false,
                            Puerto = 6011
                        },
                        new
                        {
                            Id = 13,
                            EnUso = false,
                            Puerto = 6012
                        },
                        new
                        {
                            Id = 14,
                            EnUso = false,
                            Puerto = 6013
                        },
                        new
                        {
                            Id = 15,
                            EnUso = false,
                            Puerto = 6014
                        },
                        new
                        {
                            Id = 16,
                            EnUso = false,
                            Puerto = 6015
                        },
                        new
                        {
                            Id = 17,
                            EnUso = false,
                            Puerto = 6016
                        },
                        new
                        {
                            Id = 18,
                            EnUso = false,
                            Puerto = 6017
                        },
                        new
                        {
                            Id = 19,
                            EnUso = false,
                            Puerto = 6018
                        },
                        new
                        {
                            Id = 20,
                            EnUso = false,
                            Puerto = 6019
                        },
                        new
                        {
                            Id = 21,
                            EnUso = false,
                            Puerto = 6020
                        },
                        new
                        {
                            Id = 22,
                            EnUso = false,
                            Puerto = 6021
                        },
                        new
                        {
                            Id = 23,
                            EnUso = false,
                            Puerto = 6022
                        },
                        new
                        {
                            Id = 24,
                            EnUso = false,
                            Puerto = 6023
                        },
                        new
                        {
                            Id = 25,
                            EnUso = false,
                            Puerto = 6024
                        },
                        new
                        {
                            Id = 26,
                            EnUso = false,
                            Puerto = 6025
                        },
                        new
                        {
                            Id = 27,
                            EnUso = false,
                            Puerto = 6026
                        },
                        new
                        {
                            Id = 28,
                            EnUso = false,
                            Puerto = 6027
                        },
                        new
                        {
                            Id = 29,
                            EnUso = false,
                            Puerto = 6028
                        },
                        new
                        {
                            Id = 30,
                            EnUso = false,
                            Puerto = 6029
                        },
                        new
                        {
                            Id = 31,
                            EnUso = false,
                            Puerto = 6030
                        },
                        new
                        {
                            Id = 32,
                            EnUso = false,
                            Puerto = 6031
                        },
                        new
                        {
                            Id = 33,
                            EnUso = false,
                            Puerto = 6032
                        },
                        new
                        {
                            Id = 34,
                            EnUso = false,
                            Puerto = 6033
                        },
                        new
                        {
                            Id = 35,
                            EnUso = false,
                            Puerto = 6034
                        },
                        new
                        {
                            Id = 36,
                            EnUso = false,
                            Puerto = 6035
                        },
                        new
                        {
                            Id = 37,
                            EnUso = false,
                            Puerto = 6036
                        },
                        new
                        {
                            Id = 38,
                            EnUso = false,
                            Puerto = 6037
                        },
                        new
                        {
                            Id = 39,
                            EnUso = false,
                            Puerto = 6038
                        },
                        new
                        {
                            Id = 40,
                            EnUso = false,
                            Puerto = 6039
                        },
                        new
                        {
                            Id = 41,
                            EnUso = false,
                            Puerto = 6040
                        },
                        new
                        {
                            Id = 42,
                            EnUso = false,
                            Puerto = 6041
                        },
                        new
                        {
                            Id = 43,
                            EnUso = false,
                            Puerto = 6042
                        },
                        new
                        {
                            Id = 44,
                            EnUso = false,
                            Puerto = 6043
                        },
                        new
                        {
                            Id = 45,
                            EnUso = false,
                            Puerto = 6044
                        },
                        new
                        {
                            Id = 46,
                            EnUso = false,
                            Puerto = 6045
                        },
                        new
                        {
                            Id = 47,
                            EnUso = false,
                            Puerto = 6046
                        },
                        new
                        {
                            Id = 48,
                            EnUso = false,
                            Puerto = 6047
                        },
                        new
                        {
                            Id = 49,
                            EnUso = false,
                            Puerto = 6048
                        },
                        new
                        {
                            Id = 50,
                            EnUso = false,
                            Puerto = 6049
                        },
                        new
                        {
                            Id = 51,
                            EnUso = false,
                            Puerto = 6050
                        },
                        new
                        {
                            Id = 52,
                            EnUso = false,
                            Puerto = 6051
                        },
                        new
                        {
                            Id = 53,
                            EnUso = false,
                            Puerto = 6052
                        },
                        new
                        {
                            Id = 54,
                            EnUso = false,
                            Puerto = 6053
                        },
                        new
                        {
                            Id = 55,
                            EnUso = false,
                            Puerto = 6054
                        },
                        new
                        {
                            Id = 56,
                            EnUso = false,
                            Puerto = 6055
                        },
                        new
                        {
                            Id = 57,
                            EnUso = false,
                            Puerto = 6056
                        },
                        new
                        {
                            Id = 58,
                            EnUso = false,
                            Puerto = 6057
                        },
                        new
                        {
                            Id = 59,
                            EnUso = false,
                            Puerto = 6058
                        },
                        new
                        {
                            Id = 60,
                            EnUso = false,
                            Puerto = 6059
                        },
                        new
                        {
                            Id = 61,
                            EnUso = false,
                            Puerto = 6060
                        },
                        new
                        {
                            Id = 62,
                            EnUso = false,
                            Puerto = 6061
                        },
                        new
                        {
                            Id = 63,
                            EnUso = false,
                            Puerto = 6062
                        },
                        new
                        {
                            Id = 64,
                            EnUso = false,
                            Puerto = 6063
                        },
                        new
                        {
                            Id = 65,
                            EnUso = false,
                            Puerto = 6064
                        },
                        new
                        {
                            Id = 66,
                            EnUso = false,
                            Puerto = 6065
                        },
                        new
                        {
                            Id = 67,
                            EnUso = false,
                            Puerto = 6066
                        },
                        new
                        {
                            Id = 68,
                            EnUso = false,
                            Puerto = 6067
                        },
                        new
                        {
                            Id = 69,
                            EnUso = false,
                            Puerto = 6068
                        },
                        new
                        {
                            Id = 70,
                            EnUso = false,
                            Puerto = 6069
                        },
                        new
                        {
                            Id = 71,
                            EnUso = false,
                            Puerto = 6070
                        },
                        new
                        {
                            Id = 72,
                            EnUso = false,
                            Puerto = 6071
                        },
                        new
                        {
                            Id = 73,
                            EnUso = false,
                            Puerto = 6072
                        },
                        new
                        {
                            Id = 74,
                            EnUso = false,
                            Puerto = 6073
                        },
                        new
                        {
                            Id = 75,
                            EnUso = false,
                            Puerto = 6074
                        },
                        new
                        {
                            Id = 76,
                            EnUso = false,
                            Puerto = 6075
                        },
                        new
                        {
                            Id = 77,
                            EnUso = false,
                            Puerto = 6076
                        },
                        new
                        {
                            Id = 78,
                            EnUso = false,
                            Puerto = 6077
                        },
                        new
                        {
                            Id = 79,
                            EnUso = false,
                            Puerto = 6078
                        },
                        new
                        {
                            Id = 80,
                            EnUso = false,
                            Puerto = 6079
                        },
                        new
                        {
                            Id = 81,
                            EnUso = false,
                            Puerto = 6080
                        },
                        new
                        {
                            Id = 82,
                            EnUso = false,
                            Puerto = 6081
                        },
                        new
                        {
                            Id = 83,
                            EnUso = false,
                            Puerto = 6082
                        },
                        new
                        {
                            Id = 84,
                            EnUso = false,
                            Puerto = 6083
                        },
                        new
                        {
                            Id = 85,
                            EnUso = false,
                            Puerto = 6084
                        },
                        new
                        {
                            Id = 86,
                            EnUso = false,
                            Puerto = 6085
                        },
                        new
                        {
                            Id = 87,
                            EnUso = false,
                            Puerto = 6086
                        },
                        new
                        {
                            Id = 88,
                            EnUso = false,
                            Puerto = 6087
                        },
                        new
                        {
                            Id = 89,
                            EnUso = false,
                            Puerto = 6088
                        },
                        new
                        {
                            Id = 90,
                            EnUso = false,
                            Puerto = 6089
                        },
                        new
                        {
                            Id = 91,
                            EnUso = false,
                            Puerto = 6090
                        },
                        new
                        {
                            Id = 92,
                            EnUso = false,
                            Puerto = 6091
                        },
                        new
                        {
                            Id = 93,
                            EnUso = false,
                            Puerto = 6092
                        },
                        new
                        {
                            Id = 94,
                            EnUso = false,
                            Puerto = 6093
                        },
                        new
                        {
                            Id = 95,
                            EnUso = false,
                            Puerto = 6094
                        },
                        new
                        {
                            Id = 96,
                            EnUso = false,
                            Puerto = 6095
                        },
                        new
                        {
                            Id = 97,
                            EnUso = false,
                            Puerto = 6096
                        },
                        new
                        {
                            Id = 98,
                            EnUso = false,
                            Puerto = 6097
                        },
                        new
                        {
                            Id = 99,
                            EnUso = false,
                            Puerto = 6098
                        },
                        new
                        {
                            Id = 100,
                            EnUso = false,
                            Puerto = 6099
                        },
                        new
                        {
                            Id = 101,
                            EnUso = false,
                            Puerto = 6100
                        });
                });

            modelBuilder.Entity("ContainerizationService.Models.PortAssignment", b =>
                {
                    b.HasOne("ContainerizationService.Models.MicroserviceContainer", "MicroserviceContainer")
                        .WithOne("PortAssignment")
                        .HasForeignKey("ContainerizationService.Models.PortAssignment", "MicroserviceContainerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MicroserviceContainer");
                });

            modelBuilder.Entity("ContainerizationService.Models.MicroserviceContainer", b =>
                {
                    b.Navigation("PortAssignment");
                });
#pragma warning restore 612, 618
        }
    }
}
